-- MySQL Script generated by MySQL Workbench
-- Wed Dec  6 09:48:02 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_petsitting
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_petsitting` ;

-- -----------------------------------------------------
-- Schema db_petsitting
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_petsitting` DEFAULT CHARACTER SET utf8 ;
USE `db_petsitting` ;

-- -----------------------------------------------------
-- Table `db_petsitting`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_petsitting`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(125) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  `role` ENUM('PARENT', 'SITTER', 'PARENTANDSITTER') NOT NULL,
  `date_of_birth` DATE NULL,
  `address` VARCHAR(200) NOT NULL,
  `postal_code` VARCHAR(10) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `pays` VARCHAR(45) NOT NULL,
  `about` LONGTEXT NULL,
  `accomodation_type` ENUM('FLAT', 'HOUSE') NULL,
  `living_space` DECIMAL(5,2) NULL,
  `has_vehicule` TINYINT NULL,
  `has_garden` TINYINT NULL,
  `status` ENUM('AVAILABLE', 'NOTAVAILABLE', 'BANED') NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `db_petsitting`.`animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_petsitting`.`animal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` ENUM('CAT', 'DOG') NOT NULL,
  `gender` ENUM('MALE', 'FEMALE') NOT NULL,
  `weight` DECIMAL(5,2) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `is_vaccinated` TINYINT NOT NULL,
  `is_sterilized` TINYINT NOT NULL,
  `pet_name` VARCHAR(45) NOT NULL,
  `breed` VARCHAR(45) NULL,
  `is_social` TINYINT NOT NULL,
  `pet_photo` VARCHAR(200) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_animal_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_animal_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_petsitting`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_petsitting`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_petsitting`.`service` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `daily_price` DECIMAL(5,2) NOT NULL,
  `type` ENUM('WALK', 'VISIT', 'HOSTING') NOT NULL,
  `name` VARCHAR(125) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_service_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_service_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_petsitting`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_petsitting`.`booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_petsitting`.`booking` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `total_price` DECIMAL(7,2) ZEROFILL NOT NULL,
  `animal_id` INT NOT NULL,
  `service_id` INT NOT NULL,
  `status` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_booking_animal1_idx` (`animal_id` ASC) VISIBLE,
  INDEX `fk_booking_service1_idx` (`service_id` ASC) VISIBLE,
  CONSTRAINT `fk_booking_animal1`
    FOREIGN KEY (`animal_id`)
    REFERENCES `db_petsitting`.`animal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_booking_service1`
    FOREIGN KEY (`service_id`)
    REFERENCES `db_petsitting`.`service` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



INSERT INTO `user` (`id`, `first_name`, `last_name`, `email`, `password`, `telephone`, `role`, `date_of_birth`, `address`, `postal_code`, `city`, `pays`, `about`, `accomodation_type`, `living_space`, `has_vehicule`, `has_garden`, `status`) VALUES (NULL, 'bruce', 'wayne', 'batman@fakegmail.com', '12345', '04 57 63 46 59', 'PARENTANDSITTER', '1963-07-18', 'manoir wayne\r\n\r\n', '92320 ', 'Châtillon', 'france', 'je cherchec à faire garder mon chat.', 'HOUSE', '200', '1', '1', 'AVAILABLE'), (NULL, 'dead', 'pool', 'deadpool@fakegmail.com', '12345', '09 50 63 46 59', 'SITTER', '1983-12-04', '81 Rue Jules Ferry, ', '92700 ', 'Colombes', 'france', 'je veux un animal, mais pas tout le temps.', 'FLAT', '40', '0', '0', 'AVAILABLE');



INSERT INTO `user` (`id`, `first_name`, `last_name`, `email`, `password`, `telephone`, `role`, `date_of_birth`, `address`, `postal_code`, `city`, `pays`, `about`, `accomodation_type`, `living_space`, `has_vehicule`, `has_garden`, `status`) VALUES (NULL, 'jean', 'naimarre', 'jeannaimarre@truc.com', '12345', '09 45 45 45 67', 'PARENT', '2003-12-18', '60 Rue du Moulin Vert, ', '75014 ', 'Paris', 'france', 'j\'ai un chat et une chienne à garder.', 'FLAT', '53', '1', '0', NULL), (NULL, 'Catherine', 'Tuche', 'okeiju@rtyr.com', '12345', '09 20 63 86 59', 'SITTER', '1968-02-16', '4 Rue Thérèse, ', '93170 ', 'Bagnolet', 'france', 'je suis dispo pour garder vos animaux.', 'HOUSE', '60', '1', '1', 'AVAILABLE'); 

INSERT INTO `user` (`id`, `first_name`, `last_name`, `email`, `password`, `telephone`, `role`, `date_of_birth`, `address`, `postal_code`, `city`, `pays`, `about`, `accomodation_type`, `living_space`, `has_vehicule`, `has_garden`, `status`) VALUES (NULL, 'jean', 'naimarre', 'jeannaimarre@truc.com', '12345', '09 45 45 45 67', 'PARENT', '2003-12-18', '60 Rue du Moulin Vert, ', '75014 ', 'Paris', 'france', 'j\'ai un chat et une chienne à garder.', 'FLAT', '53', '1', '0', NULL), (NULL, 'Catherine', 'Tuche', 'okeiju@rtyr.com', '12345', '09 20 63 86 59', 'SITTER', '1968-02-16', '4 Rue Thérèse, ', '93170 ', 'Bagnolet', 'france', 'je suis dispo pour garder vos animaux.', 'HOUSE', '60', '1', '1', 'AVAILABLE');

INSERT INTO `animal` (`id`, `type`, `gender`, `weight`, `date_of_birth`, `is_vaccinated`, `is_sterilized`, `pet_name`, `breed`, `is_social`, `pet_photo`, `user_id`) VALUES (NULL, 'CAT', 'MALE', '6', '2020-09-16', '1', '1', 'lechat', 'siamois', '0', NULL, '3'), (NULL, 'DOG', 'FEMALE', '40', '2013-09-19', '1', '0', 'annehidalgo', 'roquet', '0', NULL, '3'); 

INSERT INTO `animal` (`id`, `type`, `gender`, `weight`, `date_of_birth`, `is_vaccinated`, `is_sterilized`, `pet_name`, `breed`, `is_social`, `pet_photo`, `user_id`) VALUES (NULL, 'DOG', 'MALE', '34', '2016-12-11', '0', '1', 'azagoth', 'berger allemenand', '1', NULL, '4'), (NULL, 'CAT', 'FEMALE', '6', '2019-05-16', '0', '0', 'minoushka', 'angora', '1', NULL, '1');

INSERT INTO `service` (`id`, `daily_price`, `type`, `name`, `description`, `user_id`) VALUES (NULL, '15', 'WALK', 'Promenade dans un parc', 'j\'emmène votre chien dans un parc municipal avec un espace canin réservé.', '4'), (NULL, '30', 'VISIT', 'Visite à votre domicile.', 'convenu des modalités et je me rends à votre domicile pour contrôler que tout va bien.', '4');

INSERT INTO `service` (`id`, `daily_price`, `type`, `name`, `description`, `user_id`) VALUES (NULL, '25', 'HOSTING', 'Hébergement de votre animal chez moi', 'vous venez déposer votre animal avec ses croquettes (et bac et littière éventuelle) à mon domicile.', '4'), (NULL, '15', 'WALK', 'une balade en ville.', 'je promène votre animal en ville.', '2');

INSERT INTO `booking` (`id`, `start_date`, `end_date`, `total_price`, `animal_id`, `service_id`) VALUES (NULL, '2023-12-06', '2024-01-16', '15', '4', '4'), (NULL, '2023-12-26', '2024-01-08', '40', '2', '3','PENDING'');
INSERT INTO `booking` (`id`, `start_date`, `end_date`, `total_price`, `animal_id`, `service_id`) VALUES (NULL, '2024-01-14', '2024-01-26', '122', '3', '1','REJECTED');
INSERT INTO `booking` (`id`, `start_date`, `end_date`, `total_price`, `animal_id`, `service_id`) VALUES (NULL, '2024-01-14', '2024-02-29', '425', '2', '3'), (NULL, '2023-12-10', '2023-12-22', '60', '1', '2','ACCEPTED');

