#
# Will start all docker constructions with MySQL
#
# Password and network ports are handled in .env file
#
# IMPORTANT: Under Windows, it is VERY important to install a WSL 2 Distro and enable IT
#            See https://learn.microsoft.com/fr-fr/windows/wsl/install-manual#step-4---download-the-linux-kernel-update-package
version: "3.9"
name: java-petsitting-mysql
services:
  # https://hub.docker.com/_/mysql
  mysql_petsitting:
    image: mysql:8.0.32
    restart: unless-stopped
    env_file: ./.env
    container_name: mysql_petsitting
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_DATABASE=$DB_DATABASE
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_USER_PASSWORD
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    # We have two volumes
    # one file=bind: the dump of the db. This should prevail docker to
    #                mount a file 'as' a directory
    # one volume=volume: where to keep datas. It is a directory
    volumes:
      - type: bind
        source: ./petsitting_mysql_docker.sql
        target: /docker-entrypoint-initdb.d/setup.sql
        read_only: true
      - type: volume
        source: vol_mysql_petsitting
        target: /var/lib/mysql

  # https://hub.docker.com/_/phpmyadmin
  phpmyadmin_petsitting:
    image: phpmyadmin:latest
    depends_on:
      - mysql_petsitting
    container_name: phpmyadmin_petsitting
    links:
      - mysql_petsitting
    restart: unless-stopped
    ports:
      - $PMA_LOCAL_PORT:$PMA_DOCKER_PORT
    environment:
      - PMA_HOST=mysql_petsitting
      - PMA_PORT=$DB_DOCKER_PORT
      - PMA_USER=root
      - PMA_PASSWORD=$DB_ROOT_PASSWORD
      - PMA_ARBITRARY=1

volumes:
  vol_mysql_petsitting:
